# db_schema.py

# SQL DDL for Banks table
# Using SERIAL for primary key for PostgreSQL, IDENTITY for Oracle 12c+
# For older Oracle, you might need a sequence and trigger.
BANKS_TABLE_SCHEMA = """
CREATE TABLE banks (
    bank_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR(255) UNIQUE NOT NULL
)
"""

# SQL DDL for Reviews table
REVIEWS_TABLE_SCHEMA = """
CREATE TABLE reviews (
    review_pk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id VARCHAR(255) UNIQUE NOT NULL, -- Original unique ID from scraper
    review_text CLOB NOT NULL, -- CLOB for long text in Oracle, TEXT for PostgreSQL
    rating INT NOT NULL,
    review_date DATE NOT NULL,
    bank_id INT NOT NULL,
    sentiment_label VARCHAR(50),
    sentiment_score DECIMAL(5, 4),
    identified_themes VARCHAR(500), -- Store comma-separated themes
    user_name VARCHAR(255),
    app_version VARCHAR(50),
    source VARCHAR(100) NOT NULL,
    CONSTRAINT fk_bank
        FOREIGN KEY (bank_id)
        REFERENCES banks (bank_id)
)
"""